apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-xxx
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-xxx
  template:
    metadata:
      labels:
        app: java-xxx
    spec:
      containers:
      - args:
        - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
        - -XX:+UseG1GC
        - -XX:InitialRAMPercentage=25.0
        - -XX:MaxRAMPercentage=75.0
        - -XX:NewRatio=3
        - -XX:+UseAdaptiveSizePolicy
        - -XX:+UnlockExperimentalVMOptions
        - -Xloggc:/var/www/sites/logs/gc-%t.log
        - -XX:+PrintGC
        - -XX:+PrintGCDetails
        - -XX:+PrintGCDateStamps
        - -XX:+PrintTenuringDistribution
        - -XX:+PrintHeapAtGC
        - -XX:+PrintReferenceGC
        - -XX:+PrintGCApplicationStoppedTime
        - -XX:+HeapDumpOnOutOfMemoryError
        - -XX:HeapDumpPath=/usr/local/src/logs/dump-$(date '+%s').hprof
        - -Dsentry.dsn=https://53aa95c8c7994231afc06545dcafbfd2@devstagesentry.jingsocial.com/106
        - -jar
        - /usr/local/src/app.jar
        - --spring.profiles.active=prod
        command:
        - java
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: NACOS_MICRO_SERVICE_CONFIG_GROUP
          value: operation
        - name: NACOS_MICRO_SERVICE_CONFIG_DATA_ID
          value: operation-application-api-config
        envFrom:
        - configMapRef:
            name: nacos-connection-config
        image: ccr.ccs.tencentyun.com/huanghuanhui/prod-java:java-xxx
        imagePullPolicy: Always
        name: java-xxx
        ports:
        - containerPort: 8088
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /application/actuator/health
            port: 18101
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 500Mi
      imagePullSecrets:
      - name: jingsocial-image-secret